options:
  formatter: stylish
  merge-default-rules: false
files:
  include: './app/assets/sass/**/*'
rules:
  attribute-quotes: 2
  border-zero:
    - 2
    - convention: 'none'
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 2
    - allow-leading-underscore: false
  clean-import-paths: 2
  declarations-before-nesting: 2
  empty-line-between-blocks:
    - 2
    - allow-single-line-rulesets: false
  final-newline: 2
  hex-length: 2
  hex-notation: 2
  id-name-format:
    - 2
    - allow-leading-underscore: false
  indentation: 2
  leading-zero: 2
  nesting-depth:
    - 2
    - max-depth: 3
  no-color-keywords: 2
  no-color-literals: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-vendor-prefixes: 2
  one-declaration-per-line: 2
  property-sort-order:
    - 2
    - order: 'smacss'
  pseudo-element: 2
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  zero-unit: 2
